
spring.datasource.url=jdbc:mysql://localhost:3307/winekovf
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.cache.type=SIMPLE
recaptcha.secret=6LcJcggqAAAAAOBEgLvv9qdB012I_9UOsN6rma2R

server.error.include-message=always

spring.mail.host=smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=437cac8aee7bcc
spring.mail.password=e5582bc62b8137
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

